### ISSUE TITLE
Missing dependancy (Adwaita theme)

### ISSUE THREAD

**Issue by fyrak1s** [gbevan/portage-brackets-bin-overlay#3]
Hi,
your ebuild works pretty well now :) There is one issue however, when I open brackets it says the follwoing in the konsole:

`[1203/021758:ERROR:browser_main_loop.cc(192)] GTK theme error: Unable to locate theme engine in module_path: "adwaita"`

Since I am using KDE I guess I need this adwaita theme as a dependancy. Brackets looks out of place without this theme.

**Comment by gbevan** [comment]
I've added x11-themes/adwaita-icon-theme to the dependencies now.  Thanks

**Comment by gbevan** [comment]
closed as fixed
