### ISSUE TITLE
Odd char in xml

### ISSUE THREAD

**Issue by programmador** [gbevan/portage-brackets-bin-overlay#5]
I think there's an odd closing bracket in the `name` tag in repository.xml

**Comment by gbevan** [comment]
Hi.  Strange, i can't see what you are referring to.

Please note i'm nolonger maintaining this, in favour of https://github.com/gbevan/brackets-electron-bin-overlay

**Comment by programmador** [comment]
Both repos have the same issue:
https://github.com/gbevan/portage-brackets-bin-overlay/blob/master/repository.xml#L9
https://github.com/gbevan/brackets-electron-bin-overlay/blob/master/repository.xml#L9
Graham Bevan`>`

**Comment by gbevan** [comment]
I must need new glasses :-)   fixed now. thx

**Comment by programmador** [comment]
You're welcome :-)
